name: CI Pipeline

on:
 # push:
 #   branches:
#   - main
#   - 'release/*'
  pull_request:

jobs:
  ai-review-and-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run AI Code Review
        run: python scripts/ai_code_reviewer.py

      - name: Root Cause Analysis
        run: python src/agents/root_cause_bot.py

      - name: Generate UAT Suggestions
        run: python src/agents/uat_test_suggester.py
